Cyber security data analysis

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
username = "root"
password = ""
host = "localhost"
port = 3306
database = "data_analysis"

In [4]:
conn = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

In [8]:
firewall_data = pd.read_csv("../dataset/firewall_logs.csv")
firewall_data

,log_id,timestamp,source_ip,destination_ip,source_port,destination_port,protocol,action
0,1,2025-09-05 11:32:00,10.172.188.110,10.220.238.198,58807,22,TCP,ALLOW
1,2,2025-09-01 15:26:00,192.168.86.83,10.241.246.100,52614,22,UDP,DROP
2,3,2025-09-03 07:09:00,10.186.10.27,172.31.19.101,6637,8080,UDP,ALLOW
3,4,2025-09-02 01:54:00,192.168.176.67,192.168.161.160,16471,80,TCP,ALLOW
4,5,2025-09-05 10:28:00,172.21.254.189,10.167.129.115,19270,443,TCP,DENY
...,...,...,...,...,...,...,...,...
1995,1996,2025-09-02 08:06:00,192.168.63.54,192.168.21.113,29450,80,TCP,DROP
1996,1997,2025-09-07 19:39:00,172.29.18.64,172.17.187.29,27663,80,UDP,DENY
1997,1998,2025-09-01 17:43:00,172.18.8.39,192.168.62.85,37462,3389,UDP,DENY
1998,1999,2025-09-04 20:40:00,172.27.13.154,192.168.240.253,4042,3389,UDP,ALLOW
1999,2000,2025-09-02 03:40:00,172.22.120.91,192.168.156.109,37783,443,UDP,DENY

In [ ]:
weblog_data = pd.read_csv("../dataset/web_logs.csv")
weblog_data

,log_id,timestamp,client_ip,http_method,url,response_code,user_agent
0,1,2025-09-06 14:32:00,125.122.199.193,GET,/dashboard,404,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_1...
1,2,2025-09-05 18:22:00,220.195.104.118,PUT,/dashboard,200,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_0)...
2,3,2025-09-02 13:24:00,97.59.129.104,GET,/api/data,200,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...
3,4,2025-09-05 03:13:00,157.137.110.163,POST,/,200,Mozilla/5.0 (Linux; Android 2.3.2) AppleWebKit...
4,5,2025-09-04 06:51:00,200.237.104.86,GET,/search,200,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...
...,...,...,...,...,...,...,...
1995,1996,2025-09-06 23:30:00,46.53.32.38,POST,/api/data,200,Mozilla/5.0 (X11; Linux i686) AppleWebKit/532....
1996,1997,2025-09-07 01:24:00,154.174.251.33,POST,/api/data,200,Mozilla/5.0 (Windows 98; Win 9x 4.90) AppleWeb...
1997,1998,2025-09-03 05:36:00,200.106.199.129,PUT,/search,500,Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_8 like...
1998,1999,2025-09-03 15:44:00,147.20.238.194,GET,/dashboard,401,Opera/8.39.(X11; Linux x86_64; gv-GB) Presto/2...
1999,2000,2025-09-04 04:56:00,53.168.152.10,POST,/login,200,Opera/8.92.(Windows NT 5.0; nhn-MX) Presto/2.9...

In [15]:
auth_log_data = pd.read_csv("../dataset/auth_logs.csv")
auth_log_data

,log_id,timestamp,username,source_ip,destination_host,status,auth_method
0,1,2025-09-05 01:33:00,isaaccompton,192.168.118.69,db-server-01,SUCCESS,PASSWORD
1,2,2025-09-01 17:00:00,smithdarren,10.186.85.246,vpn-gateway,SUCCESS,SSH
2,3,2025-09-05 16:51:00,isaiahedwards,192.168.34.24,corp-server-01,FAILURE,PASSWORD
3,4,2025-09-03 10:48:00,danaburton,172.24.46.82,corp-server-01,SUCCESS,SSH
4,5,2025-09-07 21:23:00,christineallen,172.31.233.165,corp-server-01,SUCCESS,MFA
...,...,...,...,...,...,...,...
1995,1996,2025-09-05 12:33:00,brittanybrady,172.24.99.231,corp-server-01,FAILURE,SSH
1996,1997,2025-09-06 10:12:00,sharonolson,192.168.77.148,corp-server-02,FAILURE,MFA
1997,1998,2025-09-01 12:44:00,herrerawhitney,10.106.46.4,db-server-01,SUCCESS,PASSWORD
1998,1999,2025-09-04 04:42:00,brownshawn,172.27.70.183,db-server-01,SUCCESS,SSH
1999,2000,2025-09-05 14:36:00,edean,192.168.196.233,corp-server-02,SUCCESS,MFA

### Find the top 5 users with the most login attempts.

In [18]:
auth_log_data['username'].value_counts().reset_index().head()

    username  count
0  hwilliams      3
1      amy61      2
2  michael59      2
3   lauren60      2
4    wtaylor      2

### Count the number of failed vs successful logins per user.

In [20]:
auth_log_data.aggregate("status").value_counts().reset_index()

    status  count
0  SUCCESS   1042
1  FAILURE    958

### Identify the IP addresses with more than 50 failed login attempts in a day.

In [30]:
auth_log_data.aggregate('source_ip').value_counts().reset_index()

            source_ip  count
0      192.168.155.46      2
1       192.168.81.15      2
2      192.168.118.69      1
3        172.31.47.16      1
4      172.23.183.254      1
...               ...    ...
1993   192.168.112.18      1
1994     10.106.9.211      1
1995    10.158.54.101      1
1996  192.168.166.182      1
1997  192.168.196.233      1

[1998 rows x 2 columns]

### Find the first and last login time of each user.

In [40]:
auth_log_data['timestamp'] = pd.to_datetime(auth_log_data['timestamp'])
sorted_auth_data = auth_log_data.sort_values(by=['log_id','timestamp'])
sorted_auth_data.groupby("username").first()

,log_id,timestamp,source_ip,destination_host,status,auth_method
username,,,,,,
aaron18,284,2025-09-06 06:05:00,172.22.200.135,db-server-01,FAILURE,PASSWORD
aaronhahn,1682,2025-09-02 08:39:00,10.42.44.55,corp-server-01,SUCCESS,SSH
abigail16,308,2025-09-02 15:08:00,10.168.68.223,db-server-01,SUCCESS,SSH
abrown,898,2025-09-01 23:11:00,192.168.137.180,db-server-01,SUCCESS,PASSWORD
acolon,473,2025-09-01 00:06:00,192.168.206.152,corp-server-01,SUCCESS,SSH
...,...,...,...,...,...,...
zvaldez,442,2025-09-03 12:32:00,172.29.156.172,corp-server-01,SUCCESS,PASSWORD
zvazquez,73,2025-09-03 19:23:00,172.17.28.231,db-server-01,SUCCESS,PASSWORD
zwall,474,2025-09-03 12:41:00,192.168.79.59,vpn-gateway,SUCCESS,MFA
zwallace,139,2025-09-02 12:57:00,192.168.183.63,db-server-01,SUCCESS,PASSWORD
zwheeler,1088,2025-09-05 09:57:00,10.135.30.38,corp-server-02,SUCCESS,SSH

In [41]:
sorted_auth_data.groupby("username").last()

,log_id,timestamp,source_ip,destination_host,status,auth_method
username,,,,,,
aaron18,284,2025-09-06 06:05:00,172.22.200.135,db-server-01,FAILURE,PASSWORD
aaronhahn,1682,2025-09-02 08:39:00,10.42.44.55,corp-server-01,SUCCESS,SSH
abigail16,308,2025-09-02 15:08:00,10.168.68.223,db-server-01,SUCCESS,SSH
abrown,898,2025-09-01 23:11:00,192.168.137.180,db-server-01,SUCCESS,PASSWORD
acolon,473,2025-09-01 00:06:00,192.168.206.152,corp-server-01,SUCCESS,SSH
...,...,...,...,...,...,...
zvaldez,442,2025-09-03 12:32:00,172.29.156.172,corp-server-01,SUCCESS,PASSWORD
zvazquez,73,2025-09-03 19:23:00,172.17.28.231,db-server-01,SUCCESS,PASSWORD
zwall,474,2025-09-03 12:41:00,192.168.79.59,vpn-gateway,SUCCESS,MFA
zwallace,139,2025-09-02 12:57:00,192.168.183.63,db-server-01,SUCCESS,PASSWORD
zwheeler,1088,2025-09-05 09:57:00,10.135.30.38,corp-server-02,SUCCESS,SSH

### List users who logged in from more than 3 different countries.

In [43]:
auth_log_data[['username']].value_counts()

username
hwilliams        3
gjohnson         2
douglas28        2
tallen           2
esmith           2
                ..
harrisbarbara    1
harrellcaleb     1
harpermarc       1
haroldmccoy      1
zwheeler         1
Name: count, Length: 1977, dtype: int64

In [45]:
auth_log_data

,log_id,timestamp,username,source_ip,destination_host,status,auth_method
0,1,2025-09-05 01:33:00,isaaccompton,192.168.118.69,db-server-01,SUCCESS,PASSWORD
1,2,2025-09-01 17:00:00,smithdarren,10.186.85.246,vpn-gateway,SUCCESS,SSH
2,3,2025-09-05 16:51:00,isaiahedwards,192.168.34.24,corp-server-01,FAILURE,PASSWORD
3,4,2025-09-03 10:48:00,danaburton,172.24.46.82,corp-server-01,SUCCESS,SSH
4,5,2025-09-07 21:23:00,christineallen,172.31.233.165,corp-server-01,SUCCESS,MFA
...,...,...,...,...,...,...,...
1995,1996,2025-09-05 12:33:00,brittanybrady,172.24.99.231,corp-server-01,FAILURE,SSH
1996,1997,2025-09-06 10:12:00,sharonolson,192.168.77.148,corp-server-02,FAILURE,MFA
1997,1998,2025-09-01 12:44:00,herrerawhitney,10.106.46.4,db-server-01,SUCCESS,PASSWORD
1998,1999,2025-09-04 04:42:00,brownshawn,172.27.70.183,db-server-01,SUCCESS,SSH
1999,2000,2025-09-05 14:36:00,edean,192.168.196.233,corp-server-02,SUCCESS,MFA

### Detect suspicious accounts with login attempts from multiple IPs in a short period.

In [ ]:
auth_log_data['username'].value_counts()

username
hwilliams          3
amy61              2
michael59          2
lauren60           2
wtaylor            2
                  ..
staylor            1
carrollvictoria    1
tlewis             1
guerrerocarrie     1
edean              1
Name: count, Length: 1977, dtype: int64

## 🔑 Authentication Logs (auth_logs.csv)

### Find the top 5 users with the most login attempts.

In [47]:
auth_log_data['username'].value_counts().reset_index().head()

    username  count
0  hwilliams      3
1      amy61      2
2  michael59      2
3   lauren60      2
4    wtaylor      2

### Count the number of failed vs successful logins per user.

In [52]:
auth_log_data.groupby("username")['status'].count()

username
aaron18      1
aaronhahn    1
abigail16    1
abrown       1
acolon       1
            ..
zvaldez      1
zvazquez     1
zwall        1
zwallace     1
zwheeler     1
Name: status, Length: 1977, dtype: int64

### Count the number of blocked vs allowed connections.

In [55]:
firewall_data.aggregate('action').value_counts().reset_index()

  action  count
0   DENY    704
1  ALLOW    659
2   DROP    637

## 🌐 Web Logs (web_logs.csv)

### Find the top 10 most visited URLs.

In [68]:
weblog_data['url'].value_counts().reset_index().sort_values(by='count', ascending=False)

          url  count
0  /dashboard    359
1      /login    357
2      /admin    347
3     /search    342
4   /api/data    305
5           /    290