Netflix data analysis

In [32]:
import pandas as pd
from sqlalchemy import create_engine

In [33]:
# Database connection variables
username = "root"
password = ""
host = "localhost"   # or remote host IP
port = "3306"        # default MySQL port
database = "data_analysis"

In [34]:
conn = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

In [35]:
netflix_data = pd.read_sql("select * from netflix;", conn)

In [36]:
netflix_data.loc[netflix_data['release_year'] > 2015].sort_values(by='release_year').head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6400,s6401,Movie,Caida del Cielo,Néstor Sánchez Sotelo,"Muriel Santa Ana, Peto Menahem, Héctor Díaz, S...",Argentina,"January 20, 2017",2016,TV-MA,78 min,"Comedies, International Movies, Romantic Movies",When Julia literally falls into Alejandro's ba...
6272,s6273,Movie,Before the Flood,Fisher Stevens,Leonardo DiCaprio,United States,"February 1, 2018",2016,PG,97 min,Documentaries,Leonardo DiCaprio crisscrosses the globe to in...
6277,s6278,Movie,Beiimaan Love,Rajeev Chaudhari,"Sunny Leone, Rajneesh Duggal, Rajeev Verma, Da...",India,"November 1, 2017",2016,TV-MA,115 min,"Dramas, International Movies, Romantic Movies",After having her heart broken by a man who sed...
6279,s6280,TV Show,Being Mary Jane: The Series,,"Gabrielle Union, Lisa Vidal, Margaret Avery, O...",United States,"July 1, 2017",2016,TV-14,4 Seasons,"Romantic TV Shows, TV Dramas",Ambitious single TV journalist Mary Jane attem...
6280,s6281,Movie,Below Her Mouth,April Mullen,"Erika Linder, Natalie Krill, Sebastian Pigott,...",Canada,"August 1, 2017",2016,TV-MA,91 min,"Dramas, Independent Movies, International Movies",An engaged fashion editor begins a torrid affa...
6281,s6282,TV Show,Ben 10,,"Tara Strong, Montse Hernandez, David Kaye, Rog...",United States,"September 30, 2018",2016,TV-Y7,1 Season,Kids' TV,Ben can transform into ten types of aliens. He...
2878,s2879,Movie,Couple of Days,Tolu Awobiyi,"Lilian Esoro, Ademola Adedoyin, Enyima Nwigwe,...",Nigeria,"February 26, 2020",2016,TV-14,103 min,"Dramas, International Movies, Romantic Movies","Three couples, each in different phases of rom..."
1540,s1541,Movie,Nocturnal Animals,Tom Ford,"Amy Adams, Jake Gyllenhaal, Michael Shannon, A...",United States,"December 16, 2020",2016,R,117 min,"Dramas, Thrillers",Reading her ex-husband's violent novel manuscr...
1536,s1537,Movie,Incarnate,Brad Peyton,"Aaron Eckhart, Carice van Houten, Catalina San...",United States,"December 16, 2020",2016,PG-13,87 min,"Horror Movies, Thrillers",An unconventional demon hunter faces his great...
2882,s2883,Movie,The Arbitration,Niyi Akinmolayan,"Adesua Etomi, O.C. Ukeje, Ireti Doyle, Sola Fo...",Nigeria,"February 26, 2020",2016,TV-MA,101 min,"Dramas, International Movies",An arbitration panel is formed after a company...

In [37]:
pd.read_sql("SELECT * from netflix WHERE release_year > 2015 ORDER By release_year ASC LIMIT 10;", conn)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s7578,Movie,Neruda,Pablo Larraín,"Luis Gnecco, Gael García Bernal, Mercedes Morá...","Chile, Argentina, France, Spain, United States","June 26, 2017",2016,R,108 min,"Dramas, International Movies",When a Chilean policeman vows to find and capt...
1,s8798,TV Show,Zak Storm,,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...
2,s7581,Movie,Newtown,Kim A. Snyder,,United States,"April 7, 2017",2016,NR,84 min,Documentaries,This intimate portrait sheds light on the trau...
3,s8797,TV Show,Yunus Emre,,"Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...",Turkey,"January 17, 2017",2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves..."
4,s8795,Movie,اشتباك,Mohamed Diab,"Nelly Karim, Hany Adel, Tarek Abdel Aziz, Ahme...","Egypt, France","October 11, 2018",2016,TV-14,98 min,"Dramas, Independent Movies, International Movies",Amid the tumult following Egyptian President M...
5,s7587,TV Show,"Nightmare Tenants, Slum Landlords",,Wendi Peters,,"July 12, 2019",2016,TV-MA,2 Seasons,"British TV Shows, International TV Shows, Real...",The ongoing housing crisis in Britain has led ...
6,s8786,TV Show,YOM,,"Sairaj, Devyani Dagaonkar, Ketan Singh, Mayur ...",,"June 7, 2018",2016,TV-Y7,1 Season,Kids' TV,"With the mind of a human being, and the body o..."
7,s7594,TV Show,Nobel,,"Aksel Hennie, Tuva Novotny, Anders Danielsen L...",Norway,"December 10, 2016",2016,R,1 Season,"International TV Shows, TV Dramas, TV Thrillers",A series of incidents in Afghanistan set compl...
8,s8784,TV Show,Yoko,,"Eileen Stevens, Alyson Leigh Rosenfeld, Sarah ...",,"June 23, 2018",2016,TV-Y,1 Season,Kids' TV,"Friends Mai, Oto and Vik's games at the park b..."
9,s8783,Movie,Yoga Hosers,Kevin Smith,"Harley Quinn Smith, Lily-Rose Depp, Johnny Dep...",United States,"December 2, 2016",2016,PG-13,88 min,"Comedies, Horror Movies, Independent Movies",With an all-important high school party at sta...

Show all TV Shows directed by an Indian director.

In [39]:
netflix_data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,,,,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,,,,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...