#### Retail Sale Data

In [87]:
import pandas as pd
from sqlalchemy import create_engine

In [88]:
# Database connection variables
username = "root"
password = ""
host = "localhost"   # or remote host IP
port = "3306"        # default MySQL port
database = "data_analysis"

In [89]:
conn = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

In [90]:
retail_sale = pd.read_sql("select * from retail_sale;", conn)

In [91]:
pd.read_sql("select * from retail_sale LIMIT 10;", conn)

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantity,price_per_unit,cogs,total_sale
0,180,2022-11-05,0 days 10:47:00,117,Male,41,Clothing,3,300,129,900
1,522,2022-07-09,0 days 11:00:00,52,Male,46,Beauty,3,500,145,1500
2,559,2022-12-12,0 days 10:48:00,5,Female,40,Clothing,4,300,84,1200
3,1180,2022-01-06,0 days 08:53:00,85,Male,41,Clothing,3,300,129,900
4,1522,2022-11-14,0 days 08:35:00,48,Male,46,Beauty,3,500,235,1500
5,1559,2022-08-20,0 days 07:40:00,49,Female,40,Clothing,4,300,144,1200
6,163,2022-10-31,0 days 09:38:00,144,Female,64,Clothing,3,50,23,150
7,303,2022-04-22,0 days 11:09:00,54,Male,19,Electronics,3,30,15,90
8,421,2022-04-08,0 days 08:43:00,66,Female,37,Clothing,3,500,235,1500
9,979,2022-05-18,0 days 10:18:00,6,Female,19,Beauty,1,25,11,25

#### Retrieve all columns for sales made on 2022-11-05.

In [92]:
pd.read_sql("select * from retail_sale WHERE sale_date = '2022-11-05 LIMIT 100;';", conn)

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantity,price_per_unit,cogs,total_sale
0,180,2022-11-05,0 days 10:47:00,117,Male,41,Clothing,3,300,129,900
1,240,2022-11-05,0 days 11:49:00,95,Female,23,Beauty,1,300,123,300
2,1256,2022-11-05,0 days 09:58:00,29,Male,23,Clothing,2,500,190,1000
3,1587,2022-11-05,0 days 20:06:00,140,Female,40,Beauty,4,300,105,1200
4,1819,2022-11-05,0 days 20:44:00,83,Female,35,Beauty,2,50,14,100
5,943,2022-11-05,0 days 19:29:00,90,Female,57,Clothing,4,300,318,1200
6,1896,2022-11-05,0 days 20:19:00,87,Female,30,Electronics,2,25,31,50
7,1137,2022-11-05,0 days 22:34:00,104,Male,46,Beauty,2,500,145,1000
8,856,2022-11-05,0 days 17:43:00,102,Male,54,Electronics,4,30,9,120
9,214,2022-11-05,0 days 16:31:00,53,Male,20,Beauty,2,30,8,60
10,1265,2022-11-05,0 days 14:35:00,86,Male,55,Clothing,3,300,111,900

#### Retrieve all transactions where the category is 'Clothing' and the quantity sold is more than 4 in Nov-2022.

In [93]:
pd.read_sql("SELECT * FROM retail_sale WHERE category = 'Clothing' AND quantity > 4 AND MONTH(sale_date) = 11 AND YEAR(sale_date) = 2022;", conn)

Empty DataFrame
Columns: [transactions_id, sale_date, sale_time, customer_id, gender, age, category, quantity, price_per_unit, cogs, total_sale]
Index: []

In [94]:
retail_sale

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantity,price_per_unit,cogs,total_sale
0,180,2022-11-05,0 days 10:47:00,117,Male,41,Clothing,3,300,129,900
1,522,2022-07-09,0 days 11:00:00,52,Male,46,Beauty,3,500,145,1500
2,559,2022-12-12,0 days 10:48:00,5,Female,40,Clothing,4,300,84,1200
3,1180,2022-01-06,0 days 08:53:00,85,Male,41,Clothing,3,300,129,900
4,1522,2022-11-14,0 days 08:35:00,48,Male,46,Beauty,3,500,235,1500
...,...,...,...,...,...,...,...,...,...,...,...
1995,1857,2022-11-09,0 days 12:15:00,109,Male,60,Electronics,2,25,8,50
1996,211,2022-09-12,0 days 14:02:00,54,Male,42,Beauty,3,500,235,1500
1997,650,2023-10-08,0 days 12:41:00,98,Male,55,Electronics,1,30,15,30
1998,1211,2023-11-22,0 days 14:59:00,82,Male,42,Beauty,3,500,235,1500
1999,1650,2022-09-23,0 days 16:24:00,89,Male,55,Electronics,1,30,11,30

Calculate the total sales (total_sale) for each category.

In [95]:
pd.read_sql("SELECT category, SUM(total_sale) as Total_Sale FROM retail_sale GROUP BY category;", conn)

      category  Total_Sale
0     Clothing    311070.0
1       Beauty    286840.0
2  Electronics    313810.0

In [96]:
retail_sale.groupby("category")['total_sale'].sum().reset_index(name='Total_Sale')

      category  Total_Sale
0       Beauty      286840
1     Clothing      311070
2  Electronics      313810

Find the average age of customers who purchased items from the 'Beauty' category.

In [97]:
result = pd.read_sql("SELECT AVG(age) AS AVG_AGE FROM retail_sale WHERE category = 'Beauty';", conn)
result

   AVG_AGE
0  40.3404

In [98]:
retail_sale.loc[retail_sale['category'] == 'Beauty'].aggregate("age").mean()

np.float64(40.340390879478825)

Retrieve all transactions where the total_sale is greater than 1000.

In [99]:
result = pd.read_sql("SELECT * FROM retail_sale WHERE total_sale > 1000;", conn);
result

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantity,price_per_unit,cogs,total_sale
0,522,2022-07-09,0 days 11:00:00,52,Male,46,Beauty,3,500,145,1500
1,559,2022-12-12,0 days 10:48:00,5,Female,40,Clothing,4,300,84,1200
2,1522,2022-11-14,0 days 08:35:00,48,Male,46,Beauty,3,500,235,1500
3,1559,2022-08-20,0 days 07:40:00,49,Female,40,Clothing,4,300,144,1200
4,421,2022-04-08,0 days 08:43:00,66,Female,37,Clothing,3,500,235,1500
...,...,...,...,...,...,...,...,...,...,...,...
301,908,2022-10-30,0 days 14:47:00,64,Male,46,Beauty,4,300,81,1200
302,1805,2023-10-10,0 days 13:35:00,79,Female,30,Beauty,3,500,225,1500
303,1908,2023-12-17,0 days 12:34:00,93,Male,46,Beauty,4,300,87,1200
304,211,2022-09-12,0 days 14:02:00,54,Male,42,Beauty,3,500,235,1500
305,1211,2023-11-22,0 days 14:59:00,82,Male,42,Beauty,3,500,235,1500

In [100]:
retail_sale.loc[retail_sale['total_sale'] > 1000]

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantity,price_per_unit,cogs,total_sale
1,522,2022-07-09,0 days 11:00:00,52,Male,46,Beauty,3,500,145,1500
2,559,2022-12-12,0 days 10:48:00,5,Female,40,Clothing,4,300,84,1200
4,1522,2022-11-14,0 days 08:35:00,48,Male,46,Beauty,3,500,235,1500
5,1559,2022-08-20,0 days 07:40:00,49,Female,40,Clothing,4,300,144,1200
8,421,2022-04-08,0 days 08:43:00,66,Female,37,Clothing,3,500,235,1500
...,...,...,...,...,...,...,...,...,...,...,...
1989,908,2022-10-30,0 days 14:47:00,64,Male,46,Beauty,4,300,81,1200
1992,1805,2023-10-10,0 days 13:35:00,79,Female,30,Beauty,3,500,225,1500
1993,1908,2023-12-17,0 days 12:34:00,93,Male,46,Beauty,4,300,87,1200
1996,211,2022-09-12,0 days 14:02:00,54,Male,42,Beauty,3,500,235,1500
1998,1211,2023-11-22,0 days 14:59:00,82,Male,42,Beauty,3,500,235,1500

Find the total number of transactions made by each gender in each category.

In [101]:
pd.read_sql("SELECT gender, COUNT(transactions_id) FROM retail_sale GROUP BY gender;", conn)

   gender  COUNT(transactions_id)
0    Male                     980
1  Female                    1020

In [102]:
retail_sale.groupby("gender").aggregate("transactions_id").count().reset_index()

   gender  transactions_id
0  Female             1020
1    Male              980

Calculate the average sale for each month. Find out the best selling month in each year.

In [103]:
pd.read_sql("SELECT * FROM retail_sale;", conn)

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantity,price_per_unit,cogs,total_sale
0,180,2022-11-05,0 days 10:47:00,117,Male,41,Clothing,3,300,129,900
1,522,2022-07-09,0 days 11:00:00,52,Male,46,Beauty,3,500,145,1500
2,559,2022-12-12,0 days 10:48:00,5,Female,40,Clothing,4,300,84,1200
3,1180,2022-01-06,0 days 08:53:00,85,Male,41,Clothing,3,300,129,900
4,1522,2022-11-14,0 days 08:35:00,48,Male,46,Beauty,3,500,235,1500
...,...,...,...,...,...,...,...,...,...,...,...
1995,1857,2022-11-09,0 days 12:15:00,109,Male,60,Electronics,2,25,8,50
1996,211,2022-09-12,0 days 14:02:00,54,Male,42,Beauty,3,500,235,1500
1997,650,2023-10-08,0 days 12:41:00,98,Male,55,Electronics,1,30,15,30
1998,1211,2023-11-22,0 days 14:59:00,82,Male,42,Beauty,3,500,235,1500
1999,1650,2022-09-23,0 days 16:24:00,89,Male,55,Electronics,1,30,11,30

#### Find the top 5 customers based on the highest total sales.

In [106]:
pd.read_sql("SELECT * FROM retail_sale ORDER BY total_sale DESC LIMIT 5;", conn)

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantity,price_per_unit,cogs,total_sale
0,1743,2022-10-26,0 days 09:37:00,47,Female,34,Beauty,4,500,250,2000
1,743,2022-08-07,0 days 07:54:00,55,Female,34,Beauty,4,500,260,2000
2,1015,2022-03-09,0 days 11:53:00,94,Female,42,Electronics,4,500,200,2000
3,742,2022-03-19,0 days 06:08:00,37,Female,38,Electronics,4,500,195,2000
4,15,2022-07-01,0 days 11:50:00,75,Female,42,Electronics,4,500,210,2000